// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCydakSRj4sxEWvy0320iGx5uzagAetn30',
    appId: '1:47011577285:web:8d61d247034c8a1f27dfac',
    messagingSenderId: '47011577285',
    projectId: 'medicineapp-1e1a7',
    authDomain: 'medicineapp-1e1a7.firebaseapp.com',
    databaseURL: 'https://medicineapp-1e1a7-default-rtdb.firebaseio.com',
    storageBucket: 'medicineapp-1e1a7.firebasestorage.app',
    measurementId: 'G-9BLJ4R31N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XjRc6jFUr3IYLwh78RTu8skckZ9wR7E',
    appId: '1:47011577285:android:553ce79f125b712227dfac',
    messagingSenderId: '47011577285',
    projectId: 'medicineapp-1e1a7',
    databaseURL: 'https://medicineapp-1e1a7-default-rtdb.firebaseio.com',
    storageBucket: 'medicineapp-1e1a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdODof4ISnOeHZ4MYcjw_78h6evANffT0',
    appId: '1:47011577285:ios:482dd1488c6e9b8827dfac',
    messagingSenderId: '47011577285',
    projectId: 'medicineapp-1e1a7',
    databaseURL: 'https://medicineapp-1e1a7-default-rtdb.firebaseio.com',
    storageBucket: 'medicineapp-1e1a7.firebasestorage.app',
    iosClientId: '47011577285-bpstdt4qemld5tukd67hf8r6ebaise7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMedicineReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdODof4ISnOeHZ4MYcjw_78h6evANffT0',
    appId: '1:47011577285:ios:482dd1488c6e9b8827dfac',
    messagingSenderId: '47011577285',
    projectId: 'medicineapp-1e1a7',
    databaseURL: 'https://medicineapp-1e1a7-default-rtdb.firebaseio.com',
    storageBucket: 'medicineapp-1e1a7.firebasestorage.app',
    iosClientId: '47011577285-bpstdt4qemld5tukd67hf8r6ebaise7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMedicineReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCydakSRj4sxEWvy0320iGx5uzagAetn30',
    appId: '1:47011577285:web:947db8f2503f42a627dfac',
    messagingSenderId: '47011577285',
    projectId: 'medicineapp-1e1a7',
    authDomain: 'medicineapp-1e1a7.firebaseapp.com',
    databaseURL: 'https://medicineapp-1e1a7-default-rtdb.firebaseio.com',
    storageBucket: 'medicineapp-1e1a7.firebasestorage.app',
    measurementId: 'G-TB6B020LLP',
  );
}
